### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by poliagapitos** [g-battaglia/kerykeion#39]
**System:** Ubuntu 20.04. Python 3.8

Traceback (most recent call last):
  File "kerykeiontest.py", line 1, in <module>
    from kerykeion import KrInstance, MakeSvgInstance
  File "/home/pedja/.local/lib/python3.8/site-packages/kerykeion/__init__.py", line 141, in <module>
    from .main import KrInstance
  File "/home/pedja/.local/lib/python3.8/site-packages/kerykeion/main.py", line 13, in <module>
    from kerykeion.fetch_geonames import FetchGeonames
  File "/home/pedja/.local/lib/python3.8/site-packages/kerykeion/fetch_geonames.py", line 18, in <module>
    class FetchGeonames:
  File "/home/pedja/.local/lib/python3.8/site-packages/kerykeion/fetch_geonames.py", line 50, in FetchGeonames
    def __get_timezone(self, lat: Union[str, float, int], lon: Union[str, float, int]) -> dict[str, str]:
TypeError: 'type' object is not subscriptable

**Comment by g-battaglia** [comment]
Can you share the code that generated this error?

**Comment by poliagapitos** [comment]
It is your example:

from kerykeion import KrInstance, MakeSvgInstance

first = KrInstance("Jack", 1990, 6, 15, 15, 15, "Roma")
second = KrInstance("Jane", 1991, 10, 25, 21, 00, "Roma")

name = MakeSvgInstance(first, chart_type="Composite", second_obj=second)
name.makeSVG()
print(len(name.aspects_list))

**Comment by g-battaglia** [comment]
Mmm that's strange, I can't reproduce the error, can you give me some more information?
Can you try with different birth data?

**Comment by g-battaglia** [comment]
Ok I found the problem, since the new update kerykeion is not compatible with python 3.8, update to 3.9 and all will work!

**Comment by poliagapitos** [comment]
Ok. Thanks.
