### ISSUE TITLE
problem with the print(output(steph))

### ISSUE THREAD

**Issue by stedesDev** [g-battaglia/kerykeion#8]
It return an error:

Traceback (most recent call last):
  File "/home/steph/dev/AstroProject/test-kerykeion.py", line 21, in <module>
    print(output(steph))
  File "/home/steph/dev/AstroProject/lib/python3.8/site-packages/kerykeion/output_exemple.py", line 11, in output
    p = user.planets_house()
AttributeError: 'KrInstance' object has no attribute 'planets_house'

Process finished with exit code 1

And effectively, user, which is a kerykion instance has no attribute planets_house.  

Regards,

Steph

**Comment by Ashoka74** [comment]
Hi! I experienced the same problem here

**Comment by g-battaglia** [comment]
Hi, the problem is that in the last versione I updated the names of some functions. I'll update the readme file soon.
