### ISSUE TITLE
KerykeionChartSVG' object has no attribute 'aspects_list'

### ISSUE THREAD

**Issue by bhavishyagoyal12** [g-battaglia/kerykeion#81]
New version getting this issue 

 'KerykeionChartSVG' object has no attribute 'aspects_list'

This is stack trace

[/usr/local/lib/python3.10/dist-packages/kerykeion/charts/kerykeion_chart_svg.py](https://localhost:8080/#) in _makeAspects(self, r, ar)
   1034     def _makeAspects(self, r, ar):
   1035         out = ""
-> 1036         for element in self.aspects_list:
   1037             out += self._drawAspect(
   1038                 r,

**Comment by bhavishyagoyal12** [comment]
I tried to run on other machine now getting this

Traceback (most recent call last):
  File "C:\astore books\flatlib\planet_angle.py", line 120, in <module>
    dt = get_angles(row['date_time'].strftime("%Y/%m/%d"), gree_red)
  File "C:\astore books\flatlib\planet_angle.py", line 60, in get_angles
    name = SynastryAspects(kanye,  kanye1)
  File "C:\astore books\flatlib\ven\lib\site-packages\kerykeion\aspects\synastry_aspects.py", line 28, in __init__
    self._parse_json_settings()
  File "C:\astore books\flatlib\ven\lib\site-packages\kerykeion\aspects\natal_aspects.py", line 29, in _parse_json_settings
    settings = get_settings_dict(
  File "C:\astore books\flatlib\ven\lib\site-packages\kerykeion\settings\kerykeion_settings.py", line 219, in get_settings_dict
    settings_dict = load(f)
  File "C:\Users\dgoya\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\dgoya\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2455: character maps to <undefined>

Process finished with exit code 1

**Comment by bhavishyagoyal12** [comment]
I have reinstalled and it works
